### ISSUE TITLE
failed to convert miniraph gaf to paf with gaf2paf

### ISSUE THREAD

**Issue by gsc74** [ChriKub/gfautils#2]
(base) ubuntu@ip-172-31-45-61:/data/ZeNiX74$ gfautil -i chr22.gfa gaf2paf --gaf minigraph.gaf -o minigraph.paf
 INFO  gfautil::commands > Parsing GFA from chr22.gfa
thread 'main' panicked at 'missing cigar in GAF record', src/gaf_convert.rs:123:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ChriKub** [comment]
Hi, @gsc74 I fear you have come to the wrong repository. `gfautil` and `gfautils` are two different softwares (although they sound similar and do similar things). I tired to locate the the repository of `gfautil`, but failed as well. Maybe @ekg can help.
